### ISSUE TITLE
Error Timeout when presenting surface when alt+tab

### ISSUE THREAD

**Issue by aaravrav** [pop-os/cosmic-edit#305]
When I alt+tab from the editor to another application, if the editor is not visible after the focus switch, it freezes with the following error:
`[ERROR iced_winit::program] Error Timeout when presenting surface.`
### Specs:
```
System:
  Kernel: 6.12.9-arch1-1 arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.2.5 Distro: Arch Linux
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1070 Ti] driver: nvidia v: 565.77
  Device-2: HP w200 driver: snd-usb-audio,uvcvideo type: USB
  Display: wayland server: X.Org v: 24.1.4 with: Xwayland v: 24.1.4
    compositor: kwin_wayland driver: X: loaded: nvidia unloaded: modesetting
    gpu: nvidia,nvidia-nvswitch resolution: 1920x1080~60Hz
  API: EGL v: 1.5 drivers: nvidia,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia v: 565.77
    renderer: NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2
  API: Vulkan v: 1.4.303 drivers: N/A surfaces: xcb,xlib,wayland
```
